### ISSUE TITLE
Browser getting closed

### ISSUE THREAD

**Issue by zgtibu** [klapp101/InstagramBot#1]
Brower is getting closed when it says
DevTools listening on ws://127.0.0.1:56131/devtools/browser/cc166118-6e43-4dd3-9bc7-c19872f729ba
'WebDriver' object has no attribute 'find_element_by_name'
'WebDriver' object has no attribute 'find_element_by_xpath'

**Comment by klapp101** [comment]
I would suggestion reading up on this thread to see more about the issue that you are having. Hopefully this is beneficial to solving the issue you’re having on your end: https://stackoverflow.com/questions/72773206/selenium-python-attributeerror-webdriver-object-has-no-attribute-find-el
